export const GET_ASSET_REQUEST = 'GET_ASSET_REQUEST';
export const GET_ASSET_SUCCESS = 'GET_ASSET_SUCCESS';
export const GET_ASSET_FAILURE = 'GET_ASSET_FAILURE';

export const GET_USER_ASSET_REQUEST = 'GET_USER_ASSET_REQUEST';
export const GET_USER_ASSET_SUCCESS = 'GET_USER_ASSET_SUCCESS';
export const GET_USER_ASSET_FAILURE = 'GET_USER_ASSET_FAILURE';

export const GET_ASSET_DETAILS_REQUEST = 'GET_ASSET_DETAILS_REQUEST';
export const GET_ASSET_DETAILS_SUCCESS = 'GET_ASSET_DETAILS_SUCCESS';
export const GET_ASSET_DETAILS_FAILURE = 'GET_ASSET_DETAILS_FAILURE';