spring.application.name=CryptoTrading

server.port=${PORT:8081}

spring.jpa.hibernate.ddl-auto=update 
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/trading}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:password}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql: true

stripe.api.key = ${STRIPE_API_KEY}

razorpay.api.key = ${RAZORPAY_API_KEY}

razorpay.api.secret = ${RAZORPAY_API_SECRET}

