spring.application.name=CryptoTrading

server.port=${PORT:8081}

spring.jpa.hibernate.ddl-auto=update 
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/trading}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:password}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql: true

stripe.api.key = stripe key

razorpay.api.key = rzp_test_S3jd3iQ7hqLKPq

razorpay.api.secret = lclfUa1lliIqa1Y6WrodL1qn

